# Generated by Django 3.0.2 on 2020-01-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCAD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Section',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
                ('Section', models.CharField(max_length=2)),
                ('CA_Score', models.FloatField()),
                ('CD_Score', models.FloatField()),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCAD.Profile')),
            ],
        ),
    ]
