# Generated by Django 3.0.2 on 2020-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCAD', '0002_auto_20200109_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Section',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
