# Generated by Django 3.0.2 on 2020-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCAD', '0003_auto_20200111_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='CA_Score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='CD_Score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
